### ISSUE TITLE
Unusably slow

### ISSUE THREAD

**Issue by iceboundflame** [DVE2000/Dogbone#14]
I tried using this on a moderately complex design with maybe 30-40 components, 400 dogbone fillets to create. It doesn't complete and slows down the timeline immensely until it crashes.

For the simple/common case of making dogbones for flat-pack parts, would it work better to simply make a single sketch for all the edges in the same component (or maybe even multiple components), and do one extrude-cut operation on those circle profiles?

**Comment by iceboundflame** [comment]
Fixed in: https://github.com/caseycrogers/Dogbone/pull/15/

**Comment by caseycrogers** [comment]
Hello Iceboundflame.

These are some really awesome and major improvements/refactors! I haven't
really been working much on this project for a while so I'm glad to see you
putting a lot into it!

A lot of the decisions I made previously (sweeps instead of extrudes, one
sketch for each dogbone) were a combination of simplicity to code and
versatility (ie a dogbone fillet on an edge not perpendicular to a face).
However, given that dogbones are pretty only ever used for flatpack, I
don't think there was really any point to the versatility.

I have merged your branch with the master branch for the repository. let me
know if you come up with any more updates and I can merge them as well.

Best,
Casey
