### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by hekav** [DVE2000/Dogbone#17]
Running app on Fusoin 360 Version 2.0.2088 on mac El capitan i get
the following: ???
![dogbone](https://cloud.githubusercontent.com/assets/12659936/16185541/dbdf179a-36c4-11e6-9ad8-3ddb5a5873f0.png)

Whats wrong

**Comment by yuvalrakavy** [comment]
The problem is in line 28 where self.circStr is initialized to "cutter". If you have no parameter with this name in your design, you will get an error. I fixed it by setting:

 self.circStr = "0"

Another change that I did (and recommend) is to add after line 197:
   sketch.name = "Dogbone"

So it will be easy to know that the sketch was generated by Dogbone...

 Yuval

**Comment by LinWan3086** [comment]
Changing Line 28 in the .py was the fix for me.  :)
(Line 197 does not look the same with me though, so I left it alone)

But I noticed that in the "tool diameter box" I cannot add a user parameter, even though a video here (https://www.youtube.com/watch?v=EM13Dz4Mqnc&feature=youtu.be) claims that it did work in a earlier version.
