### ISSUE TITLE
Error Info

### ISSUE THREAD

**Issue by markus2701** [DVE2000/Dogbone#21]
![fusion360_error](https://cloud.githubusercontent.com/assets/6629158/19431073/333ddf9a-9457-11e6-97c2-a4c68c0ad80b.png)

Fusion Version: 2.0.2455

**Comment by donkey-hacket** [comment]
Same

**Comment by tjohnson250** [comment]
Same here as well. Running on Mac OS X (10.11.6)

**Comment by heartscrymusic** [comment]
Change line:28 in Dogbone.py  

From
`        self.circStr = "cutter"
`
To
`        self.circStr = "0"
`

I know I should submit a patch. I'm just not setup for that at the moment.

**Comment by ThreepE0** [comment]
there's been a pull request open on this for a while now

**Comment by caseycrogers** [comment]
Hey guys, I'm very sorry I've been so inactive. I merged the PR.

@OceansCrashing I've added you as a collaborator for the repo - you are welcome to manage it as you see fit. My priorities have shifted a lot since I wrote this script so I won't be able to effectively manage the repo myself.

**Comment by ThreepE0** [comment]
Excellent thanks very much!

On Feb 21, 2017, at 1:45 PM, caseycrogers <notifications@github.com> wrote:

Hey guys, I'm very sorry I've been so inactive. I merged the PR.

@OceansCrashing <https://github.com/OceansCrashing> I've added you as a
collaborator for the repo - you are welcome to manage it as you see fit. My
priorities have shifted a lot since I wrote this script so I won't be able
to effectively manage the repo myself.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/caseycrogers/Dogbone/issues/21#issuecomment-281437963>,
or mute the thread
