### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by tswebb71** [DVE2000/Dogbone#27]
I downloaded the latest version of Dogbone addin a few weeks ago and it ran great.  However, now, I am getting a runtime error on startup and can't get it to run at all.  HELP!

**Comment by DVE2000** [comment]
Maybe something got corrupted? You can try delete it and start Fusion. If that’s ok, re-install it and hit Shift-S, click add-ins in the dialog and click run. If it has an error, make sure the circle isn’t spinning (hit stop if it is) and click the down arrow next to “run” and choose Debug. Spyder will come up. See if it says anything. Click the continue button (could be twice, can’t remember) and see what happens when you try create dogbones in Fusion. That’s all I got...

**Comment by tswebb71** [comment]
I tired that to no avail.  Here is the error I get.  It shuts down the add-in every time.  Like I said, it worked for several weeks, then out of the blue, I get this error.

<img width="520" alt="screen shot 2018-02-18 at 8 19 09 pm" src="https://user-images.githubusercontent.com/36607715/36360397-28c8ee6a-14e9-11e8-8308-340a0b4e55e1.png">

**Comment by tswebb71** [comment]
Got it.  reinstalled it for about the 4th time and it worked.  No idea what I did.  LOL

**Comment by DVE2000** [comment]
Hmm. From that traceback, the resource for the button wasn’t found. That’s the picture used for the Dogbone button. It’s in a directory called Resources in the Dogbone dir.
