### ISSUE TITLE
Error trying to create first dogbone

### ISSUE THREAD

**Issue by CptanPanic** [DVE2000/Dogbone#30]
So I click on a body that is rotated so that all the edges that need dogbones are heading up towards z, and I get this error.  I also tried selecting the edge manually.

![image](https://user-images.githubusercontent.com/4087170/39843919-7682750c-53bb-11e8-8b25-41ebd76d930a.png)

**Comment by DVE2000** [comment]
That's interesting. It seems to be caused by the progress dialog trying to be created. I love the buginess of Fusion360. Only thing I can think of to help is for you to comment out all the lines with "progressDialog" using a pound sign (#) at the beginning of the line. This would be in the Dogbone.py file. And then stop and re-start the add-in if Fusion is already running.

**Comment by marvingreenberg** [comment]
> I love the buginess of Fusion360.

Jeez.  You should try writing a plugin for Sketchup sometime. 😉

**Comment by DVE2000** [comment]
😂😂😂😂

**Comment by CptanPanic** [comment]
Looks like I just had the dogbone in the wrong direction as I had it as the default in the z axis, but was really in the y axis.
