### ISSUE TITLE
error when clicking dogbone button

### ISSUE THREAD

**Issue by raptordemon** [DVE2000/Dogbone#34]
![dogbone error](https://user-images.githubusercontent.com/2067745/48513985-4db8e200-e82b-11e8-9b64-f9a7138785f4.PNG)
Hi i am getting the following error when clicking the dogbone button.

i have tried reinstalling dogbone. i am using fusion 360 2.0.4860

im not sure where to start debugging!

thanks
Raptor

**Comment by pludikar** [comment]
Hi @raptordemon 

Looks like something has corrupted a variable called self.circStr, and unfortunately the error you sent isn't totally explicit on what's going on.  So I'm going try an experienced guess.

1. Could you open a file explorer and go to %AppData%\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns
2. If the directory contains a file called default.dat - please delete it and run Dogbone again.

Let me know if that has solved the problem, or if you need help to follow these steps.

If the problem persists, we'll have to try another tack, and, if you are up to it, we'll have to work together to figure out what is going on.

Regards
Peter

**Comment by raptordemon** [comment]
that fixed it! thanks so much, this tool is awesome!!

**Comment by yurtkuran** [comment]
Hello...having the similar issue. Receive the following error message when creating the dogbone. I'm running version 2.0.5103. Any help is greatly appreciated. Thanks!

![image](https://user-images.githubusercontent.com/9701952/49690496-03601380-fb00-11e8-9ce4-69c3cdf40c1c.png)

**Comment by pludikar** [comment]
Hi Erol,

It looks like you are using the parametric mode - f360 has a heap load of issues  creating holes in anything other than simple components.  If you are trying to make a dogbone on a component that is a copy , then try making the dogbone(s) on the original component (ie the component with :1 at the end of the name - it’ll be the earliest version in the timeline).

If that fails, please try making a hole in the component that is having trouble (we just want to determine if f360 is or isn’t at fault, so the hole can be anywhere):
- make the component active (the dot next to the component in the browser should be clicked on)
- add a hole (H on the keyboard)
- reference two edges and specify a reasonable distance (say 1/2 in or 13mm - actual distance is not important)
- create a hole depth by selecting “To” and selecting a face on the opposite side of the component

If f360 throws an error, then it’s a bug in f360, otherwise it’s a dogbone app issue.  If it’s an f360 error, I would suggest you report it to Autodesk. If it’s an app issue, could you send me a copy of your model.

Unless you are desperate to use the parametric mode, In the interim I would suggest you use the static mode - which will require you to delete the dogbones and re-do them is you change any of the model dimensions.

Let me know if any of this helps

Regards
Peter

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by basti3000** [comment]
> 
> 
> Hi @raptordemon
> 
> Looks like something has corrupted a variable called self.circStr, and unfortunately the error you sent isn't totally explicit on what's going on. So I'm going try an experienced guess.
> 
>     1. Could you open a file explorer and go to %AppData%\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns
> 
>     2. If the directory contains a file called default.dat - please delete it and run Dogbone again.
> 
> 
> Let me know if that has solved the problem, or if you need help to follow these steps.
> 
> If the problem persists, we'll have to try another tack, and, if you are up to it, we'll have to work together to figure out what is going on.
> 
> Regards
> Peter

Worked for me as well after this error, Thanks heaps! Fantastic addin:
![2020-04-09](https://user-images.githubusercontent.com/63414027/78914776-3109f380-7a8b-11ea-85f1-b0eadba715d3.png)
