### ISSUE TITLE
readDefaults failing

### ISSUE THREAD

**Issue by knickels** [DVE2000/Dogbone#38]
So it seems to be failing on startup, with reading the defaults.dat file somewhere.  This is on a mac, I used the binary installer to install.  Thanks for any pointers.

<img width="381" alt="Screen Shot 2019-04-06 at 5 32 16 PM" src="https://user-images.githubusercontent.com/4690486/55676037-1c03ee80-5892-11e9-9c74-8e7597c6629b.png">

**Comment by knickels** [comment]
I had an old version of the add-in installed.  When I found the install files, removed them, and re-installed, it started working.

**Comment by DVE2000** [comment]
The defaults.dat file would be found in the directory that contains Dogbone.py. In your case it appears to be /Users/knickels/Library/..../Addins/Dogbone/

Try delete it if it exists and restart Dogbone. If it still fails, I’ll check to see what Peter did.

To be able to see your Library directory in Finder, you’ll have to Google. It’s not hard. Otherwise, you can access it from Terminal.

**Comment by DVE2000** [comment]
That’s because the old defaults.dat was removed when you deleted the original dir. :)

**Comment by pludikar** [comment]
Hi Gary,
just so you know I have a version on Github that does a validity check on the .dat file and resets it - default-datacheck branch.  I haven't merged it yet, but I think it's ready.

Peter
________________________________
