### ISSUE TITLE
Use of user parameters for parametric dogbones breaks using plugin multiple times with different settings

### ISSUE THREAD

**Issue by ksperling** [DVE2000/Dogbone#39]
In my particular case I was trying to apply mortise dogbones to one set of components, and minimal dogbones to another. What seems to happen is that as soon as the dogbone plugin is launched again, any changes to settings cause the `db*` user parameters to be updated (this even seems happens immediately, without the need to hit "OK"), which breaks any other parameteric dogbone operations that are already in the timeline.

Would it be possible to "inline" the relevant expressions into the Hole operations directly rather than using user parameters? This way multiple independent sets of dogbone operations can be used. Note that this shouldn't even break the ability for the user to update parameters like tool diameter manually, simply by creating their own user parameters and referencing them from the dogbone settings.

E.g. in my example of the short side mortise with diameter `ToolDiameter` I currently get Hole operations with cut diameter `dbRadius * 2` and parameters
```dbRadius = ( dbToolDia + dbOffset ) / 2
dbToolDia = ToolDiameter
dbOffset = 0
dbHoleOffset = dbRadius
```

Instead I'm suggesting that the generated Hole operations end up with a diameter expression like `((ToolDiameter) + (0)) / 2 * 2`, without any additional user parameters being created or modified. (Obviously in this case the expression could be simplified to just `ToolDiameter` but it's probably unnecessary for the plugin to optimise this.)

**Comment by pludikar** [comment]
HI Karsten,
I've just arrived back from a trip, and my head's still operating 6hrs behind what it got used to.

Unfortunately F360 has a bunch of issues around parametric design - it's not caused by the dogbone app.  Once the app has finished placing the dogbones, it's not involved any more.  I've often found that changing the thickness of, say, a board that make up the sides of a cabinet - I then have to fix the model to make it usable again.

One way to achieve what I think you are looking for is to create the parametric dogbones for one type of dogbone.  Then go into the parameter dialog and rename the db* parameters to, eg db*1 - so, dbToolDia1, dbOffset1 and dbHoleOffset1.  By doing that, the changes will automatically ripple through to the holes that have just been created.  When you restart the app, it will apply dbToolDia, dbOffset and dbHoleOffset to any new dogbone it creates leaving the ones you changed previously alone.

I've not been happy with the stability and speed of the app in F360 for a while, and I'm in the process of changing the design to allow dogbones to be manually refreshed, by simply opening and closing the app.  I still have a little way to go, but the basic static creation essentially works, and in comparison to the existing method, it's blazingly fast - it can create over 400 dogbones in less than 10 seconds.  The present approach could take 20 or so minutes.  I think this is the way to go, and I suspect that parametric mode will become a thing of the past - at least until autodesk become willing to actually spend time fixing some basic functionality in F360, rather than creating new functionality.

Peter

**Comment by ksperling** [comment]
Hi Peter,

thanks for the quick response. At the moment I'm only dealing with a much smaller number of dogbones (10s rather than 100s) so the performance isn't as much of a problem for me. I've opened a PR with my fix if you're interested. Is there a github branch that has this improved refreshable static mode that you're talking about?

Thanks, Karsten

**Comment by pludikar** [comment]
Hi Karsten,
Most users will rarely get into the 100s of dogbones, but you do start seeing performance issues even at 10-20 dogbones.  At this number the new version will create the dogbones almost instantly.  If you are interested you can find the branch [here](https://github.com/DVE2000/Dogbone/tree/restore-selection-onCreate).  Be aware, though, it is a work in progress and should be regarded as a proof of concept - many features are not working, and I would say it's probably 50-60% operational.  I've just started playing with concepts to allow the refresh - so none of that works.

Peter
