### ISSUE TITLE
Parametric holes lose link to reference geometry

### ISSUE THREAD

**Issue by ksperling** [DVE2000/Dogbone#41]
It seems like changing a parameter that affects the geometry that parameteric dogbones have been applied to frequently makes them lose their "link" to the geometry. E.g. if I change my `MaterialThickness` parameter from 18mm to 19mm about half or more of my dogbones holes disappear. I'm using parametric minimal dogbones.

I've been manually experimenting with a hybrid between the static and parametric approaches provided by the addon, namely using the sketch the static approach generates, but then editing that sketch to tie the points to the referenced geometry (and the hole feature to plug the correct variables for diameter etc back in). Apart from being pretty tedious to do by hand it seems to work well and correctly tracks geometry changes.

For standard / minimal dogbones, a construction circle around the drill point with radius `ToolDiameter * 1.1 / sqrt(2)` with tangent constraints to the two edges seems to work. For the mortise case the hole center can be directly constrained to be on the relevant edge with the correct distance to the corner.

I'm not sure if this approach would have a negative impact on performance due to being sketch-based, but at least to me having the dogbones work in a fully parametric fashion is much more important.

**Comment by pludikar** [comment]
Hi Karsten,
Just to add to the response I left on the other thread - most F360 features incur a significant processing overhead due to internal checks, calculations and knock on effects.  Most of the time this isn't too critical when writing a script, but it becomes noticeable when an addon, such as this dogbone, starts sifting through many edges, faces, bodies etc in order to find the appropriate edges to apply dogbones to.  Unfortunately, the sketch feature adds yet another layer of checks and overhead on top of the basic features, and if it then includes any kind of projection it adds more layers to the processing overhead.  It quickly becomes bogged down, particularly if there are more than a handful of candidate dogbone edges.  If you look at the original code created by Casey Rodger's original addon and Patrick Rainsberry's improvement - both contain notes which show that they tried hard to avoid using the sketch feature.  N my personal experience I would wholeheartedly agree with them.

I think that once the next update of the addon goes online, it'll be the best option available.  The new code is on Github, but currently not in fit a state to make public.  If you are interested in helping, you'd be very welcome to join in.

Peter
