### ISSUE TITLE
No longer working after Fusion update

### ISSUE THREAD

**Issue by michaelh1300** [DVE2000/Dogbone#47]
This plugin has been amazing, and super helpful. Unfortunately, it's no longer working for me. I feel like this could have happened with the recent fusion update as I haven't changed anything, or done anything differently than in the past. I'm getting a "Failed: Traceback... RuntimeError:2:InternalValdationError..." 

See photo.  Thanks in advance.

![Screen Shot 2020-05-19 at 3 54 04 PM](https://user-images.githubusercontent.com/53943150/82335527-c1701800-99e9-11ea-81ca-15e367686beb.png)

**Comment by pludikar** [comment]
Hi @michaelh1300 ,

Sorry for the delay in responding.  It looks like you have a corrupted default file.  I should probably write a wiki because you are the second (known) person to have had this issue.  It's usually easy to fix.

- open file explorer and go to %AppData%\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns

- the directory should contain a file called default.dat - please delete it and run Dogbone again.

-  if that fails, you may have to stop and run it again from the add-ins dialog

Let me know if that has solved the problem, or if you need further help.  

I will be checking the validity of this file in future releases - still a work in progress, because F360 changed their development environment before Christmas, and it stopped working for more sophisticated developments - and they still haven't fixed it (at least of the previous update).

Peter

**Comment by michaelh1300** [comment]
Amazing, that worked perfectly. Thanks, and that response was quite fast.
