### ISSUE TITLE
Add command to manufacturing model environment

### ISSUE THREAD

**Issue by nmk456** [DVE2000/Dogbone#51]
There's a relatively new feature in Fusion 360 called manufacturing models, where you can create a version of model that only exists in the manufacturing workspace. It's useful to simplify or modify designs so they can be manufactured, which is exactly what this plugin does. It would be nice if the dogbone command could show up in the manufacturing model workspace instead of or in addition to the main workspace. I've tried to modify the plugin myself, but I couldn't get it to work. I'm not sure if it's just because I don't understand the Fusion 360 API well enough or if the feature is new enough that they haven't updated the API for it yet.

**Comment by pludikar** [comment]
Hi @nmk456

Sorry for the delay in response.  I'll have a look at adding the button to the manufacturing model, I can't think it won't.  Although F360 API can be temperamental, to put it mildly.  You sometimes have to jump through hoops to get the simplest of things to work.

I don't mean to rant, but personally I dislike the way AD has implemented the manufacturing model - I'm pretty sure it was done mostly for the Nesting feature that they're working on, and it really doesn't play nicely with the rest of the system.  It looks and feels like they've reinvented the wheel, and I strongly suspect they've done that because the nesting feature is loosely based on TruNest which is fundamentally a 2D paradigm, and they've tried to mesh it with F360 which is a 3D paradigm.  I think they've headed in the wrong direction.

 I'll have a look at this and get back to you when I can.

Peter

**Comment by binaryben** [comment]
This would be very handy. Can this be added to the manufacturing workspace please?

**Comment by pludikar** [comment]
@binaryben 
Unfortunately, I’d forgotten that this was requested, given the pandemic and, more particularly, I was having major stability issues with the development environment. I think Autodesk has made some improvements recently, and I’ve been able to work on some projects without having to restart F360 every 20 minutes.  Thank you for reminding me, I’ll look into what possibilities are available, and I’ll try to get back to you as soon as practicable 

regards 
Peter

**Comment by pludikar** [comment]
@binaryben @nmk456 

Just to let you know - I've added the dogbone button to the Manufacturing Workspace.  I'm not expecting any issues, but if there are any please let me know.  

I've only updated the main file (Dogbone.py) in this repository.  So, to update your version you need to either download the zip file (Green Code Button -> download zip), or just download the main file (click [here](https://github.com/DVE2000/Dogbone/blob/master/Dogbone.py), right click "raw" button and then select "save as".

For Windows: 
If you download the zip:  extract to %appdata%/Autodesk\Autodesk Fusion 360\API\AddIns .  You will have to delete the existing Dogbone folder and rename the newly extracted folder from Dogbone-master to Dogbone.

If you downloaded the file: you will need to replace the main file with the one you've just downloaded.  The file location is %appdata%/Autodesk\Autodesk Fusion 360\API\AddIns\Dogbone

For Mac:
Similar to above except the folder location is "/Users/<your username>/Library/Application Support/Autodesk/Autodesk Fusion 360/APl/Addlns" and "/Users/<your username>/Library/Application Support/Autodesk/Autodesk Fusion 360/APl/Addlns/Dogbone" repectively.

Regards
Peter

**Comment by JoshWaldner** [comment]
This Add-on works great in the manufacturing models. i was a bit hesitant to using the addon since i thought i needed to select all the edges manually to apply the dogbone, but i got a surprise at the power of it. however i have a minor issue that it is not applying to all pieces of the faces i selected. i have to select multiple times to apply to all the corners. i was just wondering if this is to be expected and has a reason why, or is it to be worked on in the future?

**Comment by pludikar** [comment]
Hi @JoshWaldner 

The addin is supposed to automatically select all valid corners associated with all faces that you select.  However, at the moment, it will only work with faces that are parallel to each other.  If it doesn’t then it’s something I will need to correct. 

If you have a screen shot, or better still, a model you are working on that you are willing to upload. Then I can have a closer look at it.  

Peter

**Comment by JoshWaldner** [comment]
i go ta screen recording of what i am trying to tell
let me know if you cant make out
https://user-images.githubusercontent.com/105467383/224506271-cf408e61-9677-4aa7-b554-adf33d7454d6.mp4

**Comment by pludikar** [comment]
@JoshWaldner 
For some reason I’m not getting a video, but I do see a thumbnail, and I think that tells me what I need to know.  Can I assume that each component/part is separate and individual?

If you have copies of any component, the addin should only allow you to select a single copy - because the dog bones will automatically be applied to all copies (which is a natural characteristic of components).  If one or more of the copies are upside down relative to the original selected copy, then the addin may get confused.  It’s not a behaviour I would want and I’ll look into fixing it.

 I have several similar nested situation as you appear to have, so I’ll have a look at a my models to see if I get the same and I’ll get back to you as soon as I can

Peter

**Comment by pludikar** [comment]
@JoshWaldner 
Sorry for the delay in getting back to you.  I had a try with my version of a nested model (in my case 4 sides, back and shelf), and dogbones were successfully created on every part the first time.  I also tried it in both design workspace and manufacturing model with no problem.  

 It appears that there may be some quirk with your model that the add-in is having problems with.  To be sure the add-in actually works with a variety of models would you be good enough to save your model as a .f3d file and upload it here?  

If you happen not to know how to create a .f3d model - it's found under the file menu as export.

Regards
Peter

**Comment by JoshWaldner** [comment]
@pludikar 
it does not let me upload a .f3d, or a zip file here, can you give me your email address and i will sent a file to you direct?

**Comment by pludikar** [comment]
@JoshWaldner 
Sure it’s: Peter at ludikar dot com

regards
Peter

**Comment by pludikar** [comment]
Hi @JoshWaldner 

I've fixed the selection issue and merged the changes into the master.  On the model you sent me (thanks BTW), I can select all the panels/parts and they get dogbones applied to them.  Unfortunately it does create some blank sketches in the process - I'm working on refactoring the whole AddIn, I'll fix that as part of that exercise.

I've changed the method I've used to handle F360 events, so unless you download all the files (probably the easiest), you will need to download dogbone.py, decorators.py and dbutils.py.  Let me know if there any issues.

Peter

**Comment by pludikar** [comment]
I'm closing this issue - at least for the time being

**Comment by binaryben** [comment]
Sorry, I haven't had a chance to test it. Writing docs for how to use the CNC at my local community shed 😅

Thanks for your work on this and I'm fine with it being closed. Can reopen if there is an issue and I'll try to remember to confirm it's working when I go to use it again
