### ISSUE TITLE
InternalValidationError: isExists

### ISSUE THREAD

**Issue by it-ony** [DVE2000/Dogbone#53]
After selecting the Dogbone command, I get 

```
Failed:
Traceback (most recent call last):
File "/Users/tony/Library/Application Support/
Autodesk/Autodesk Fusion 360/APl/Addlns/Dogbone/
dbutils.py", line 174, in notify
notify_method(args)
File "/Users/tony/Library/Application Support/
Autodesk/Autodesk Fusion 360/APl/Addlns/Dogbone/
Dogbone.py", line 341, in onCreate
modeRowInput.Iistltems.add(IStaticI, not
self.parametric, 'resources/staticModeI )
File "/Users/tony/Library/Application Support/
Autodesk/webdeploy/production/
380d70885f263236bcd663557495fe325106a36d/
Autodesk Fusion 360.app/Contents/Api/Python/
packages/adsk/core.py", line 9019, in add
return _core.Listltems_add(seIf, *args)
RuntimeError: 2 : InternalValidationError : isExist
```

**Comment by pludikar** [comment]
@it-ony 
Hi Tony,

It's a problem with Macs and a relatively recent OS update that forces case sensitive folder names - It was an oversight at my end, sorry about that.

The easiest fix is to go to "/Users/tony/Library/Application Support/Autodesk/Autodesk Fusion 360/APl/Addlns/Dogbone"  and change the **R**esource folder name to **r**esource.  I believe all other subfolder names are capitalized correctly.

This was also raised in issue #48.  I was planning to release a new version of the dogbone addIn earlier this year, but a severe bug in F360's development environment made it almost impossible to do anything meaningful - hopefully that is being fixed in their next release in January.

Peter
