### ISSUE TITLE
Not a parametric design

### ISSUE THREAD

**Issue by n-davies** [DVE2000/Dogbone#54]
I turned off history (before sending out a model to be cut) and running DogBone produced the error

> Failed:
> Traceback (most recent call last):
> File "C:/Users/nikko/ AppData/Roaming/Autodesk/Autodesk Fusion 360/
> API/AddIns/Dogbone\dbutils. py”, line 174, in notify
> notify_method(args)
> File "C:/Users/nikko/ AppData/Roaming/Autodesk/Autodesk Fusion 360/
> API/AddIns/Dogbone/Dogbone. py”, line 651, in onExecute
> self.createStaticDogbones()
> File "C:/Users/nikko/ AppData/Roaming/Autodesk/Autodesk Fusion 360/
> API/AddIns/Dogbone/Dogbone. py”, line 969, in createStaticDogbones
> startTiMarker = self.design.timeline.markerPosition
> File "C:/Users/nikko/ AppData/Local/ Autodesk /webdeploy/production/
> a95f8cSced1169cf841c8219266ac15fc1536633/ Api/Python/
> packages\adsk\fusion.py”, line 15719, in _get_timeline
> return _fusion.Design__get_timeline(self)
> RuntimeError: 3 : this is not a parametric design

Perhaps a simpler error message stating that Design History needs to be enable for DogBone to run would be an improvement.  Otherwise, working like a charm.

**Comment by pludikar** [comment]
Hi @n-davies 

That's a problem I fixed about a year ago, but I didn't update the self extracting files because I was expecting to bring out a better version of the AddIn - F360 thwarted that by dropping a significant bug into the development environment - they've only just fixed it, after a year of being persistent with them.

If you download the Dogbone.py in the github code area, and use it to replace the one that's in the API, it'll not only give you a better message, but also give you the option to switch history back on - adds a couple of other minor bug fixes too.  I can guide you if you need help replacing the file - just let me know.

Peter
