### ISSUE TITLE
InternalValidationError : input->evaluateStringAndUpdateUI

### ISSUE THREAD

**Issue by Ashteroide** [DVE2000/Dogbone#55]
I've recently downloaded this and had this issue on multiple occasions when I previously used it, regardless of mode and whenever I change to a different design I get the error:
```
Failed:
Traceback (most recent call last):
  File "C:/Users/home/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone\dbutils.py", line 174, in notify
    notify_method(args)
  File "C:/Users/hom/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 324, in onCreate
    adsk.core.ValueInput.createByString(self.circStr))
  File "C:/Users/home/AppData/Local/Autodesk/webdeploy/production/e69ac0f55aa8512db83c718906bbdedf0daa2f89/Api/Python/packages\adsk\core.py", line 5940, in addValueInput
    return _core.CommandInputs_addValueInput(self, id, name, unitType, initialValue)
RuntimeError: 2 : InternalValidationError : input->evaluateStringAndUpdateUI(xlVal->valueAsIString(), dTemp, bValueStrChanged)
```

Computer: Lenovo L13 Yoga
OS: Windows 10

Dogbone v2.0

If there are any new versions of this by someone else, please can you link it?

**Comment by pludikar** [comment]
Hi @Ashteroide

at the moment I’m not 100% sure, but it looks like the file that holds the default values has been corrupted.  Go through the steps outlined [here](https://github.com/DVE2000/Dogbone/issues/47) and that will probably fix the issue.  If it doesn’t, then post back here and we’ll get to the bottom of the problem. 

Peter

**Comment by Ashteroide** [comment]
Hi @pludikar 
I was able to delete the file, I used the Dogbone tool on a shape, then made a new design and was able to use Dogbone again. Though I have the suspicion it's to do with parameters in certain designs. Since the `Tool Diameter` (In the Dogbone menu) goes to each design, I use a custom paremeter called `toolDiameter = 6.35mm` in Fusion's parameters, and in any case where I switch design and is there is no `toolDiameter` it creates an error. But just putting in `6.35mm` keeps it working across all designs, so I'll make sure to remember to create a parameter called `toolDiameter` for each design.

And sure enough that's the case, I just tested it in Fusion360.

the parameter `dbToolDia` is created by DogBone so I won't use `toolDiameter`, I have some experience in Python so I forked this repository and I'll make some edits of my own. Thank you for the help :)

**Comment by pludikar** [comment]
Hi @Ashteroide 
How do you use `toolDiameter`?  Do you try to enter it as "`toolDiameter`" into the dogbone dialog, or as a value?  Unfortunately I've not implemented the ability to accept parameter names into the dialog - although I may in the future.

One suggestion - if you are using the same `toolDiameter` value all the time, then dogbone addin will keep track of the last value of `toolDiameter` and pre-fill the value as the default, the next time you use the AddIn - no matter whether you create a new design or use an existing design.

If you are using the addIn in the parameteric mode (ie dogbones automatically adjust when you change the design parameters), then there's nothing to stop you using `dbToolDia` instead of `toolDiameter`, or if you want to keep some independence, then set the parameter value of `toolDiameter` to `dbToolDia` then everything should keep track.  You then only need to change the Tool Diameter in the addIn, and your design should follow suit.

Be aware, however, that parametric mode can be slow if you have a relatively medium to large design complexity.  It's also prone to underlying F360 bugs, most of which were supposed to have been fixed, but F360 team aren't the most reliable bug fixers.

If you need help and/or clues to de-cyphering the code, I'll be happy to assist.  I was working on a new version, but F360 changed from Spyder to VSC a couple of years ago, and, along with that, they introduced a show stopping bug.  That bug has been fixed - took them over a year - but I've not been able to get back to working the new code.  Hopefully I'll revive the work in the winter.  The new code is being completely refactored, and the design approach changed to take a bigger advantage of Python's OOD capabilities - so it'll look more professional, and easier to debug, when I'm done :-)

Peter

**Comment by Ashteroide** [comment]
> Hi @Ashteroide
> How do you use `toolDiameter`? Do you try to enter it as "`toolDiameter`" into the dogbone dialog, or as a value? Unfortunately I've not implemented the ability to accept parameter names into the dialog - although I may in the future.

I set the parameter in Fusion360 at `toolDiameter` and then put that into the dogbone dialog. I might just stick to it creating `dbToolDia` and use that instead, I usually only used `toolDiameter` for rounding corners so the machine could handle it.



> If you are using the addIn in the parameteric mode (ie dogbones automatically adjust when you change the design parameters), then there's nothing to stop you using `dbToolDia` instead of `toolDiameter`, or if you want to keep some independence, then set the parameter value of `toolDiameter` to `dbToolDia` then everything should keep track. You then only need to change the Tool Diameter in the addIn, and your design should follow suit.

I'll make sure to set it to parametric as majority of my projects use parameters.



> F360 team aren't the most reliable bug fixers

That much is true, I've encountered many bugs that still haven't been fixed and have been brought up multiple times.

> If you need help and/or clues to de-cyphering the code, I'll be happy to assist.

I think I'll finish off some other coding projects first, then see if I can work on it. Though Python is not something I'm fully familiar with, but I could give it a try and look through a bit of documentation. And thank you for the offer.

> Hopefully I'll revive the work in the winter. The new code is being completely refactored, and the design approach changed to take a bigger advantage of Python's OOD capabilities - so it'll look more professional, and easier to debug, when I'm done :-)

That would be nice to see!
