### ISSUE TITLE
RuntimeError: 5 : Unable to create hole. Height was negative or zero. Modeling Error: Can't create hole toolbody, please check inputs

### ISSUE THREAD

**Issue by ride4sun** [DVE2000/Dogbone#56]
I am getting this error when I run the addin on a simple model:

```
Failed:
Traceback (most recent call last):
  File "C:/Users/ride4/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone\dbutils.py", line 174, in notify
    notify_method(args)
  File "C:/Users/ride4/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 644, in onExecute
    self.createParametricDogbones()
  File "C:/Users/ride4/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 948, in createParametricDogbones
    holes.add(holeInput)
  File "C:/Users/ride4/AppData/Local/Autodesk/webdeploy/production/4c84784f9b312b4c6ccb78d46529ebb70d7a5a09/Api/Python/packages\adsk\fusion.py", line 20877, in add
    return _fusion.HoleFeatures_add(self, input)
RuntimeError: 5 : Unable to create hole.
Height was negative or zero.
Modeling Error: Can't create hole toolbody, please check inputs

```

**Comment by pludikar** [comment]
@ride4sun 

it looks like you are using the dogbone app in parametric mode.  This error is typically associated with bugs in Fusion 360.  Most of the time Fusion 360 behaves itself, but unfortunately it’s not perfect.  In the past F360 had a major bug creating copies and mirrors of bodies. They seem to have fixed most of these issues but they’re not great at following up on bug reports, so I can’t say for certain. 

If you are keen to stay in the parametric mode, then try creating a simple hole on the face (press H, then click on the face in question). Once you walk through the hole dialog, you will probably get the same error on completion. That will basically prove or disprove whether F360 is at fault or not. If it is F360 then you may need to change your model bodies to avoid mirroring or the creation method you used on that body. You should also check that the face has been created properly.   I’d be happy to look at your model if you want to make it available to me. 

Otherwise I’d suggest switching the app mode to static (hover your mouse over the dialog icons to see the modes). Static has tended to be more robust, but it also means that if you change the underlying model dimensions the dog bones will end in the wrong place and you have to delete them and start over - a bit of a pain, but doesn’t happen too often

regards
Peter
