### ISSUE TITLE
'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by it-ony** [DVE2000/Dogbone#58]
I'm on master branch and when creating a parametric dogbone on a simple design I get the following error logged

```
2023-09-12 23:12:24,966 ; dogbone.decorators ; ERROR ; 104; onExecute_handler error termination
Traceback (most recent call last):
  File "/Users/tony/Development/fusion/Dogbone/decorators.py", line 101, in notify
    notify_method(*handler_args, eventArgs)  #notify_method_self and eventArgs come from the parent scope
  File "/Users/tony/Development/fusion/Dogbone/Dogbone.py", line 654, in onExecute
    self.createParametricDogbones()
  File "/Users/tony/Development/fusion/Dogbone/Dogbone.py", line 819, in createParametricDogbones
    if len(selectedFace.selectedEdges.values()) <1:
AttributeError: 'list' object has no attribute 'values'
```

Before clicking the OK button, the correct edges are highlighted. A static dogbone is working. As this is a runtime error related to invoke `values()` which isn't existing, it seems unrelated to my design.

```bash
$ python --version
Python 3.10.13
```

I don't know, if my python version is used of if fusion ships with an own env.

**Comment by pludikar** [comment]
I think that may be my oversight after doing a significant update early this year.  I'll have a look at it and let you know.

F360 effectively imports/creates its own python environment whenever a python add-in is invoked.  That way it ensures that the appropriate version of python is being invoked, although 3.10 seems about right, if I remember correctly. Some of the later/newer versions of python syntax and features won't work unfortunately.

Not too many people have used the parametric version of dogbones, largely because it is slow on anything other than the simplest model. I'm planning to deprecate parametric once Autodesk clears up a new api feature they're been touting for almost 3 years, which would allow features such as dogbones be automatically updated whenever the underlying body is changed.  It may be a while still before that happens, so I'll keep the parametric dogbone alive in the meantime.

Peter




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tony Findeisen ***@***.***>
Sent: Tuesday, September 12, 2023 5:33:35 PM
To: DVE2000/Dogbone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DVE2000/Dogbone] 'list' object has no attribute 'values' (Issue #58)


I'm on master branch and when creating a parametric dogbone on a simple design I get the following error logged

2023-09-12 23:12:24,966 ; dogbone.decorators ; ERROR ; 104; onExecute_handler error termination
Traceback (most recent call last):
  File "/Users/tony/Development/fusion/Dogbone/decorators.py", line 101, in notify
    notify_method(*handler_args, eventArgs)  #notify_method_self and eventArgs come from the parent scope
  File "/Users/tony/Development/fusion/Dogbone/Dogbone.py", line 654, in onExecute
    self.createParametricDogbones()
  File "/Users/tony/Development/fusion/Dogbone/Dogbone.py", line 819, in createParametricDogbones
    if len(selectedFace.selectedEdges.values()) <1:
AttributeError: 'list' object has no attribute 'values'


Before clicking the OK button, the correct edges are highlighted. A static dogbone is working. As this is a runtime error related to invoke values() which isn't existing, it seems unrelated to my design.

$ python --version
Python 3.10.13

I don't know, if my python version is used of if fusion ships with an own env.

**Comment by pludikar** [comment]
This was definitely my coding error - I forgot to update the parametric function, after changing how the hole objects were handled.  It now doesn't throw the runtime error, but it will incorrectly position dogbones on corners that are not at 90 degrees.  I'll work on that over the next few days.  Let me know if there are any further issues.
Peter

**Comment by pludikar** [comment]
It should be working as expected now with version 2.1.2

**Comment by it-ony** [comment]
Thanks Peter for the fix. Works. 

>  I'm planning to deprecate parametric once Autodesk clears up a new api feature they're been touting for almost 3 years, which would allow features such as dogbones be automatically updated whenever the underlying body is changed.

I'm waiting for the update since ever and lost hope that it will be [available soon](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-FA7EF128-1DE0-4115-89A3-795551E2DEF2). I tried to get it working with the finger join plugin, but the update methods are not called. 

> Q: When will custom features be released?
> A: There is no planned date when Fusion will release the custom feature functionality. Custom features will move out of preview when it's believed the functionality is stable and the functionality delivered provides enough capabilities to be useful.

**Comment by pludikar** [comment]
Phew!  I tested it, but not exhaustively - so, good to hear it worked.

I’ve lost hope that custom features will be released soon too. If you’ve been on the API forum you will have seen that I tried getting answers from Patrick Rainsberry, but it was easier to get light out of a black hole. I noticed that custom features isn't pinned anymore.

I would have implemented some of the API, but I was worried that AD would pull the custom features altogether which would leave the dogbone app in a poor situation.  I'm keeping my fingers crossed though.

Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
