### ISSUE TITLE
I don't think this handles acute angles correctly

### ISSUE THREAD

**Issue by sprior** [DVE2000/Dogbone#6]
Draw a sketch with an inside feature that includes line segments that form an acute angle, maybe 30 degrees.  Then extrude and dogbone it.  It looks to me like the router bit still won't be able to cut the corner.
![untitled](https://cloud.githubusercontent.com/assets/3361800/12108635/f7b39db6-b347-11e5-8462-9e4881a17830.png)

**Comment by caseycrogers** [comment]
Yeah so unfortunately it doesn't quite handle that right. It'd need to lines tangent to the circle leaving and connecting to the edge. I left that out because I was concerned about the stability of Fusion 360's constraint solver-the two lines might blow up and wobble all over the place and cause problems when moving the dogbones.

I don't do much milling my self, but I think most CAM tools will just automatically cut the excess material when trying to cut the given path?

If you think it's important to support let me know and I'll try it out tomorrow and see if there are any reliability issues.

**Comment by Helmi** [comment]
I do use dogbone fillets quite often and can't imagine a situation where i would need them for other angles than 90deg - probably that's just me.

A good way to handle these would then be to ignore other angles completely to not accidentally get these stuff done when doing a complete part. But maybe we'll soon hear a reason why dogbones would be needed on other angles, too.

**Comment by sprior** [comment]
Admittedly I was just trying out the code so I did that little squiggle and tried to dogbone it.  I've been using Fusion for 3D printing and just got started in CNC, so I'm not sure of usecases yet, but it would seem to make sense to me that if you needed to make a hole to fit a tenon that it's possible the tenon could have non-right angles.  The first thing I'd suggest is that any features that can't be handled correctly should be excluded for now (do no harm).  I was trying to brainstorm how this could be handled and I was thinking along the lines of bisecting the angle between the faces and making a slot along the bisection line from the tip to the first face that center line intersects (yes that will be longer than necessary, but it'll be cutting empty space).  That means the edges of the slot will trim the narrow area, but nothing else.

**Comment by DVE2000** [comment]
I believe that being able to specify the minimum and maximum allowed angle for edges in a selected body fixes this. To actually cut a doggone in a highly acute angle, you'd probably have to add an extra radius or take care of it manually.
