### ISSUE TITLE
Parametric integration

### ISSUE THREAD

**Issue by Helmi** [DVE2000/Dogbone#7]
I don't know much about the Fusion360 API but would it be possible to get the Dogbone fillets done in a more parametrical way to be able to change the size of the fillets later when you for example change your mind and use another tool size?

**Comment by caseycrogers** [comment]
Hey Helmi,
There's definitely a way to do that! It's not really practically implementable from within the API because once the Dogbone Fillets are created my Add-in stops running and loses all control.

However, if you create some user variables from the user parameters tool (found in the modify section) you can name two parameters, one for the tool diameter and one for the offset (say "toolDiam" and "toolOff"). If you use the dogbone tool and use toolDiam and toolOff as your input sizes you can then change the two parameters whenever you want and the Dogbones will update to reflect your changes.

**Comment by Helmi** [comment]
oh that is good to know - thanks.

**Comment by caseycrogers** [comment]
No problem, let me know if you have any other questions or comments!
